version: '3.8'

services:
  etcd:
    container_name: quantum-index-etcd
    image: quay.io/coreos/etcd:v3.5.5
    platform: linux/arm64
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd:delegated
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      time  container_name: quantum-index-minio
  image: minio/minio:RELEASE.2023-03-20T20-16-18Z
  platform: linux/arm64
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  volumes:
    - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data:delegated
  command: minio server /minio_data --console-address ":9001"
  deploy:
    resources:
      limits:
        memory: 2G
        cpus: '1'
      reservations:
        memory: 1G
        cpus: '0.5'
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
    start_period: 20s
  restart: unless-stopped
  ports:
    - "9000:9000"
    - "9001:9001"

vector-store:
  container_name: quantum-index-milvus
  image: milvusdb/milvus:v2.3.3
  platform: linux/arm64
  command: ["milvus", "run", "standalone"]
  environment:
    - ETCD_ENDPOINTS=etcd:2379
    - MINIO_ADDRESS=minio:9000
    - CACHE_SIZE=4GB
    - ENABLE_GPU=false
    - SEARCH_CACHE_SIZE=1GB
    - INDEXING_THRESHOLD=1024
  volumes:
    - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus:delegated
    - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus_logs:/var/lib/milvus/logs:delegated
  deploy:
    resources:
      limits:
        memory: 6G
        cpus: '2'
      reservations:
        memory: 3G
        cpus: '1'
  ports:
    - "19530:19530"
    - "9091:9091"
  depends_on:
    etcd:
      condition: service_healthy
    minio:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9091/health"]
    interval: 30s
    timeout: 20s
    retries: 3
    start_period: 30s
  restart: unless-stopped

  container_name: quantum-index-cortex
  build:
    context: .
    dockerfile: services/cortex/Dockerfile
  platform: linux/arm64
  environment:
    - PYTORCH_ENABLE_MPS_FALLBACK=1
    - METAL_DEVICE_WRAPPER_TYPE=1
    - PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.8
    - PYTORCH_MPS_LOW_WATERMARK_RATIO=0.6
    - MILVUS_HOST=vector-store
    - MILVUS_PORT=19530
    - CORTEX_API_KEY=${CORTEX_API_KEY:-dev_key}
    - MPS_ENABLE_DEVICE=1
    - METAL_DEBUG_LAYER=1
  volumes:
    - .:/app:delegated
    - ~/.cache/huggingface:/root/.cache/huggingface:delegated
  deploy:
    resources:
      limits:
        memory: 12G
        cpus: '4'
      reservations:
        memory: 6G
        cpus: '2'
  ports:
    - "8000:8000"
  depends_on:
    vector-store:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 30s
  restart: unless-stopped

volumes:
  milvus:
    driver: local
