name: quandex
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - fastapi>=0.104.1
  - uvicorn>=0.24.0
  - pydantic>=2.6.0
  - httpx>=0.25.0
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.25.0
  - scipy>=1.11.3
  - networkx>=3.2.1
  - pandas>=2.1.4
  - rich>=13.7.0
  - ipython>=8.20.0
  - tqdm>=4.66.1
  - pytest>=7.4.3
  - pip
  - pip:
    - transformers>=4.35.2
    - sentence-transformers>=2.2.2
    - langchain>=0.0.344
    - openai>=1.3.0
    - pyobjc-framework-metal>=10.1
    - textual>=0.44.1
    - faiss-cpu>=1.7.4
    - pypdf>=4.0.1
    - prompt_toolkit>=3.0.43
    - pytest-asyncio>=0.21.1
    - pytest-cov>=4.1.0
    - websockets>=12.0
    - python-multipart>=0.0.6
