name: quantum-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  # Core ML dependencies will be installed via pip for better Metal support
  - pip:
    # ML/AI with Metal support
    - torch
    - torchvision
    - torchaudio
    - transformers>=4.35.2
    - sentence-transformers>=2.2.2
    # Vector store
    - pymilvus>=2.3.3
    # API and UI
    - fastapi>=0.104.1
    - uvicorn>=0.24.0
    - pydantic>=2.4.2
    - textual>=0.47.1
    - rich>=13.7.0
    - httpx>=0.25.0
    - websockets>=12.0
    # Development
    - pytest
