name: quantum-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  # Core ML dependencies will be installed via pip for better Metal support
  - pip:
    # ML/AI with Metal support
    - torch
    - torchvision
    - torchaudio
    - transformers>=4.35.2
    - sentence-transformers>=2.2.2
    - accelerate>=0.25.0
    - optimum>=1.16.1
    # LLM Integration
    - llama-index>=0.9.11
    - langchain>=0.0.350
    - ctransformers>=0.2.27
    # Vector store
    - pymilvus>=2.3.3
    # Quantization and Optimization
    - bitsandbytes>=0.41.3
    - auto-gptq>=0.5.1
    # API and UI
    - fastapi>=0.104.1
    - uvicorn>=0.24.0
    - pydantic>=2.4.2
    - textual>=0.47.1
    - rich>=13.7.0
    - httpx>=0.25.0
    - websockets>=12.0
    # Q-Fabric Components
    - networkx>=3.2.1
    - qiskit>=1.0.0
    - pennylane>=0.33.1
    # Neural Loom Integration
    - jax>=0.4.20
    - flax>=0.7.5
    - optax>=0.1.7
    # Development
    - pytest
    - hypothesis>=6.92.1
    - black>=23.12.0
    - mypy>=1.7.1
    # Install Metal requirements
    - -r requirements-metal.txt
