quantum_nexus:
  # Q-Fabric Configuration
  qortex:
    thread_group_size: 256
    quantum_state_size: 1024
    metal_optimization: true
    memory_pool_size: 8192  # 8GB unified memory allocation
  
  # Quantum Orchestrator
  orchestrator:
    max_parallel_states: 16
    state_coherence_time: 1000  # milliseconds
    measurement_interval: 100   # milliseconds
    metal_compute_units: 8
  
  # Neural Loom
  neural_loom:
    model_type: "gguf"
    quantization: "q4_k_m"
    context_size: 8192
    metal_threads: 4
    batch_size: 32
  
  # Superposition UI
  quantum_ide:
    refresh_rate: 60  # Hz
    max_parallel_views: 4
    metal_rendering: true
    shader_optimization: true
