apiVersion: v1
kind: Service
metadata:
  name: cortex
spec:
  selector:
    app: cortex
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vector-store
spec:
  selector:
    app: vector-store
  ports:
  - port: 19530
    targetPort: 19530
    name: milvus
  - port: 9091
    targetPort: 9091
    name: metrics
  type: ClusterIP
