name: Documentation
on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - 'src/q0rtex/**/*.py'
jobs:
  docs:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mdx_truly_sane_lists
      - name: Build documentation
        run: mkdocs build --strict
      - name: Generate API docs
        run: |
          pip install pdoc3
          pdoc --html --output-dir docs/api src/q0rtex
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

