name: Pixee

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

permissions:
  contents: write
  pull-requests: write
  security-events: write  # For security findings

jobs:
  pixee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Pixee
        uses: pixee/workflow-action@v1
        with:
          auto-fix: true
          save-to-file: security-fixes.diff
          fail-on-high: true  # Fail on high severity issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Additional security checks
      - name: Run security scan
        if: always()  # Run even if Pixee fails
        run: |
          # Check for sensitive files
          ! find . -type f -exec grep -l "BEGIN.*PRIVATE KEY" {} \;
          ! find . -type f -exec grep -l "api[_-]key" {} \;
          
          # Verify license headers
          find . -name "*.py" -exec grep -l "Copyright" {} \;
          
          # Check for unsafe patterns
          ! grep -r "eval(" .
          ! grep -r "subprocess.call" .
          
      - name: Run dependency scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
